In [1]:
import numpy as np

 <h4>1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.</h4>

In [5]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


<h4>2. Write a NumPy program to get help with the add function.</h4>

In [7]:
np.info(np.add)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same precision as the platform integer is used.
out : ndarray, optional
    Alternative output 

<h4>3. Write a NumPy program to test whether none of the elements of a given array are zero. 
</h4>

In [19]:
arr= np.array([0,1,2,3,4])
np.all(arr != 0)

False

<h4>5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).</h4>

In [21]:
arr= np.array([1,6,7,np.inf,-np.inf])
np.isfinite(arr)

array([ True,  True,  True, False, False])

<h4>6. Write a NumPy program to test elements-wise for positive or negative infinity. </h4>

In [22]:
arr= np.array([-np.inf, 9, 8, 0, np.inf])
print(np.isposinf(arr))
print(np.isneginf(arr))

[False False False False  True]
[ True False False False False]


<h4>7. Write a NumPy program to test element-wise for NaN of a given array.</h4>

In [23]:
arr= np.array([np.inf,-np.inf,np.nan, 23])
np.isnan(arr)

array([False, False,  True, False])

<h4>8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. </h4>

In [30]:
arr= np.array([1+2j, 1+1j, 3, 3.1, 2j])
print(np.iscomplex(arr))
print(np.isscalar(2.5))
print(np.isreal(arr))

[ True  True False False  True]
True
[False False  True  True False]


<h4>9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.</h4>

In [32]:
a= np.array([1.1,1.002,1.2])
b= np.array([2.0,1.009,1.0001])
np.allclose(a,b)

False

<h4>10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.</h4>

In [39]:
arr1= np.array([99, 45, 33, 23])
arr2= np.array([9,33,22,110])
print(np.greater(arr1,arr2))
print(np.greater_equal(arr1, arr2))
print(np.less(arr1,arr2))
print(np.less_equal(arr1,arr2))

[ True  True  True False]
[ True  True  True False]
[False False False  True]
[False False False  True]


<h4>11. Write a  NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.</h4>

In [46]:
arr1= np.array([23,22,45,67.5])
arr2= np.array([23,22,45,67.49999])
print(np.equal(arr1,arr2))
print(np.allclose(arr1,arr2))

[ True  True  True False]
True


<h4>12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.</h4>

In [50]:
arr= np.array([1,7,13,105])
arr.nbytes

16

<h4>13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. </h4>

In [55]:
a= np.zeros(10)
b= np.ones(10)
c= np.full(10, 5)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


<h4>
    14. Write a NumPy program to create an array of integers from 30 to 70.
</h4>

In [57]:
arr= np.arange(30, 71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

<h4>15.Write a NumPy program to create an array of all even integers from 30 to 70.</h4>

In [59]:
arr= np.arange(30,71,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

<h4>16. Write a NumPy program to create a 3x3 identity matrix.</h4>

In [60]:
arr= np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h4>17. Write a NumPy program to generate a random number between 0 and 1.</h4>

In [65]:
a= np.random.random()
a

0.9065083668548636

<h4>18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.</h4>

In [66]:
num= np.random.normal(0,1,15)
num

array([ 0.00109881,  0.04073905,  0.52925407,  0.94941153,  0.98486928,
        0.67565106,  0.3224187 , -0.61657047, -0.18104926, -0.24819834,
        0.15492738,  0.81615935, -1.09782711,  0.73918827,  0.92945082])

<h4>19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.</h4>

In [69]:
arr= np.arange(15,55)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


<h4>20. Write a NumPy program to create a 3X4 array and iterate over it.</h4>

In [77]:
arr= np.arange(12).reshape((3,4))
for e in arr.flat:
    print(e)

for e in np.nditer(arr):
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11


<h4>21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.</h4>

In [78]:
arr= np.linspace(5,50,10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

<h4>22. Write a  NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.</h4>

In [80]:
arr= np.arange(21)
arr[9:16] *= -1
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

<h4>23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.</h4>

In [87]:
arr= np.random.randint(0,10,5)
arr

array([6, 2, 2, 9, 0])

<h4>24. Write a NumPy program to multiply the values of two given vectors.</h4>

In [89]:
a= np.array([5,5,3,1])
b= np.array([5,4,4,0])
a * b

array([25, 20, 12,  0])

<h4>25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.</h4>

In [93]:
arr= np.arange(10,22).reshape((3,4))
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

<h4>26. Write a NumPy program to find the number of rows and columns in a given matrix.</h4>

In [98]:
arr= np.arange(10,22).reshape((3,4))
arr.shape

(3, 4)

<h4>27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.</h4>

In [99]:
i_arr= np.eye(3)
i_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h4>28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.</h4>